export const client = {
  name: "R and J Landscapes London",
  tagline: "Professional Landscaper in Aylesbury — Quality You Can Trust",
  description: "Professional landscaper services in Aylesbury and surrounding areas. Trusted local experts with 26 Google reviews.",
  category: "Landscaper",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Aylesbury",
  county: "",
  postcode: "",
  basedIn: "Aylesbury",
  founderName: "Jason",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "5",
  reviewCount: "26",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "graham fisher", rating: 5, text: "Very pleased with the quality of work and standard of finish. Work involved removal of front door step, replacing with a large area of porcelain paving, steps to front door and a ramp for wheelchair access. Communication was good and the site was kept clean. I'm delighted to recommend R & J Landscapes", date: "4 months ago" },
    { name: "Lindsay Oakman", rating: 5, text: "Could not be happier, it was an absolute delight to work with everyone at R & J Landscapes, its not often you can say that these days, their work was first class, they even took away my old fence for me which was not part of the original quote! I would definitely use & them again & absolutley recommend this company.", date: "6 months ago" },
    { name: "David Howells", rating: 5, text: "I needed a number of fence panels replacing and a new wooden side gate installed. Jason came round to survey the site and provided an estimated cost. He clearly explained some options so that my needs could be met. He also provided an estimated timeline for when the work might be completed. Having agreed the work should go ahead, I was subsequently phoned by Daphne to confirm an appointment slot for the work (a week before the appointment), this was in line with the original timeline estimate given. On the day, the team arrived and successfully completed the work giving me updates as appropriate and the ability to view the work as it progressed. The work was completed as per the original cost estimate. Really happy with the work done and the team cleaned up everything after them. Daphne was great coordinating all the admin activities, and everything proceeded from first visit to completion as expected with no cause for any concern. Thanks to everyone for the work done, and I wouldn't hesitate to contact Jason again for any future landscaping needs.", date: "8 months ago" },
    { name: "Stephen Low", rating: 5, text: "My wife and I are absolutely delighted with the support and guidance we have had from Jason and for the excellent work done by Jaly and his team who were thorough, careful and who worked hard for us. Everyone was polite and friendly.  Jaly is a perfectionist and very skilful. All the work was done to the highest standard and included sorting out the drainage, laying porcelain tiles and a front drive, fencing and a new gate and creating flower beds, including some very good soil. Throughout the build we were kept informed of what was being done and of what would be done next and given ample time to review the work, ask questions and to make decisions where necessary.  Jaly paid close attention to the brief and to what we asked for and made several helpful suggestions, most of which we gladly agreed with and which definitely improved the end result. The final build is of very high quality; everything was left clean and tidy and we could not be happier with the result.", date: "10 months ago", badge: "Local Guide" },
    { name: "Keith Puleston", rating: 5, text: "We had a long and old flagstone garden path that needed replacement.  We had several quotes and Jason came and provided an estimate for block paving.  His professional approach was obvious, and also his quote was the highest, but we went with R&J Landscaping.  Work like this has to be done superbly, as you expect it to last for many decades.  We are absolutely delighted with the work carried out.  Beautifully laid path with no damage to the surrounding lawn, the work was done in a week.  The team on the job were excellent and cleared up the site with the skip removed the day after completion,  Highly recommended.", date: "11 months ago" },
    { name: "Chirag Pradhan", rating: 5, text: "Jason and his team absolutely nailed it! From the initial meeting, Jason knew exactly what we wanted and carried out the works efficiently and professionally. The team Jason sent were very courteous and a pleasant to deal with. I was also getting the electrical stuff done in the garden at the same time as the turf was laid out and Jason’s team adjusted their work routine with the electrician without making any fuss about it. And Daphne was great with the communication too. Exactly what you would expect from a professional company. I would highly recommend Jason and his team for any landscaping work you have!!", date: "11 months ago", badge: "Local Guide" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "R and J Landscapes London | Professional Landscaper in Aylesbury",
    description: "Professional landscaper in Aylesbury. 5 stars on Google with 26 reviews. Quality workmanship guaranteed.",
  },
};
